["pd_nc_sr_lda_stringent_0.4.1_upf"]
extension = "upf"
functional = "lda"
version = "0.4.1"
git-tree-sha1 = "d7fdc17d088c5c7e87a7a107bec744a33e4338e2"
lazy = true

    [["pd_nc_sr_lda_stringent_0.4.1_upf".download]]
    sha256 = "ba0c16c557f24e39b0b71d64a1ba3582421e016ce7a9cc799c4de195b7c4ec21"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_sr_lda_stringent_0.4.1_upf.tar.gz"

["pd_paw_pbe_standard_1.1_xml"]
extension = "xml"
functional = "pbe"
version = "1.1"
git-tree-sha1 = "a38f7fd6c4620a5907836d7f6584e84b03be33ce"
lazy = true

    [["pd_paw_pbe_standard_1.1_xml".download]]
    sha256 = "83c288b1356d4322c51ebef61975e1434bbf5eb303a82d41c0f4b076958b9beb"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_paw_pbe_standard_1.1_xml.tar.gz"

["pd_nc_sr_lda_standard_0.4.1_upf"]
extension = "upf"
functional = "lda"
version = "0.4.1"
git-tree-sha1 = "1ea71a84cf375286564538a9cab789991f4bf1f4"
lazy = true

    [["pd_nc_sr_lda_standard_0.4.1_upf".download]]
    sha256 = "7606cfa6d1cfab22ff584c548d13fc37872ec648c5c4f6636ee7b1221277128a"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_sr_lda_standard_0.4.1_upf.tar.gz"

["pd_nc_fr_pbesol_stringent_0.4_upf"]
extension = "upf"
functional = "pbesol"
version = "0.4"
git-tree-sha1 = "2266c8ad653947a27f2eb1d9af3de98f71188eca"
lazy = true

    [["pd_nc_fr_pbesol_stringent_0.4_upf".download]]
    sha256 = "21a655020524f9996e8cd422ce273f883452fba12023365e948aa79a815e374a"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_fr_pbesol_stringent_0.4_upf.tar.gz"

["pd_nc_sr_pbe_stringent_0.4.1_upf"]
extension = "upf"
functional = "pbe"
version = "0.4.1"
git-tree-sha1 = "56094b8162385233890d523c827ba06e07566079"
lazy = true

    [["pd_nc_sr_pbe_stringent_0.4.1_upf".download]]
    sha256 = "63b71d31f22b06965c9dd484d406d3deb63ea21b58d7b658727f09d210850d72"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_sr_pbe_stringent_0.4.1_upf.tar.gz"

["pd_nc_fr_pbesol_standard_0.4_upf"]
extension = "upf"
functional = "pbesol"
version = "0.4"
git-tree-sha1 = "1e84458e63d03a0b5c5f8c78e821cf339c349400"
lazy = true

    [["pd_nc_fr_pbesol_standard_0.4_upf".download]]
    sha256 = "85689ac3ad52f73420041740a3333c912c0598e3fac524e6c81ac1f94f203797"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_fr_pbesol_standard_0.4_upf.tar.gz"

["pd_nc_sr_pbesol_standard_0.4.1_upf"]
extension = "upf"
functional = "pbesol"
version = "0.4.1"
git-tree-sha1 = "28297a392c83dd3cfe302bb26ecf270d28ca360f"
lazy = true

    [["pd_nc_sr_pbesol_standard_0.4.1_upf".download]]
    sha256 = "56a9b15cac540357a67cf33b3219af59962bbaa7d4a1bac5b7dab72ed2462e88"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_sr_pbesol_standard_0.4.1_upf.tar.gz"

["pd_nc_sr_pbe_standard_0.4.1_upf"]
extension = "upf"
functional = "pbe"
version = "0.4.1"
git-tree-sha1 = "897b9d17527039dd86ca882603c3af2ea0c0aada"
lazy = true

    [["pd_nc_sr_pbe_standard_0.4.1_upf".download]]
    sha256 = "1ee2aec5d651012557ebcfcd33d7a3192e4789b1c49af1bd846a6f7c6a032f84"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_sr_pbe_standard_0.4.1_upf.tar.gz"

["pd_nc_fr_pbe_standard_0.4_upf"]
extension = "upf"
functional = "pbe"
version = "0.4"
git-tree-sha1 = "ee1a7f52bd3cc257af0b6325a0647337d4ab2396"
lazy = true

    [["pd_nc_fr_pbe_standard_0.4_upf".download]]
    sha256 = "1edd99303e7965091741be4286d9b6e3e1673fa3e8936a24a7ecd33dccc74985"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_fr_pbe_standard_0.4_upf.tar.gz"

["pd_nc_fr_pbe_stringent_0.4_upf"]
extension = "upf"
functional = "pbe"
version = "0.4"
git-tree-sha1 = "1abeaf58df0209381808aaf999cdfa9b2f9023c0"
lazy = true

    [["pd_nc_fr_pbe_stringent_0.4_upf".download]]
    sha256 = "cbef5a89d0b14c11ca161e34decfc11046069590a40cb2fb709fa5abf696bbcd"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/pd_nc_fr_pbe_stringent_0.4_upf.tar.gz"
