name = "PseudoPotentialData"
uuid = "5751a51d-ac76-4487-a056-413ecf6fbe19"
authors = ["Michael F. Herbst <info@michael-herbst.com> and contributors"]
version = "0.1.2"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Artifacts = "1"
Compat = "4.16"
LazyArtifacts = "1"
TOML = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
